### ISSUE TITLE
Extension Incompatibility

### ISSUE THREAD

**Issue by PwrSrg** [coliff/Brackets-HTML5CodeHints#6]
Your extensions completely breaks cfBrackets - http://cfbrackets.org

**Comment by coliff** [comment]
I checked out that 'CFBrackets' Extension, it uses a very similar method for adding the additional code hints. Unfortunately, only one can be installed at a time. My 'HTML5CodeHints' extension sets the code hints at a higher priority therefore disabling the CFBrackets ones. I hope Brackets core fixes this issue.
